<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
  https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.projects</groupId>
<artifactId>humanitarian-logistics-java-core</artifactId>
<version>1.0</version>

<properties>
  <maven.compiler.source>17</maven.compiler.source>
  <maven.compiler.target>17</maven.compiler.target>
  <javafx.version>26.0.1</javafx.version>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <main.class>com.project.Main</main.class>
  <javafx.maven.plugin.version>0.08</javafx.maven.plugin.version>
</properties>
<dependencies>
  <dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>${javafx.version}</version>
  </dependency>

  <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.19.1</version> 
</dependency>

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>5.8.0</version>
</dependency>

  <dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-fxml</artifactId>
    <version>${javafx.version}</version>
  </dependency>

  <dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-web</artifactId>
    <version>${javafx.version}</version>
  </dependency>

  <dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>jdk-jsobject</artifactId>
    <version>${javafx.version}</version>
  </dependency>

  <!-- google gson (for json) -->
  <dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.11.0</version>
</dependency>
</dependencies>

<build>
  <sourceDirectory>src/main/java</sourceDirectory>
  <testSourceDirectory>src/test</testSourceDirectory>
  <resources>
    <resource>
      <directory>src/main/java</directory>
      <includes>
        <include>**/*.fxml</include>
        <include>**/*.css</include>
        <include>**/*.html</include>
      </includes>
    </resource>
  </resources>

  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>3.11.0</version>
      <configuration>
        <!-- <excludes> -->
          <!--   <exclude>**/hedspi/test/**/*.java</exclude> -->
          <!-- </excludes> -->
        <failOnError>true</failOnError>
      </configuration>
    </plugin>

    <plugin>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-maven-plugin</artifactId>
      <version>0.0.8</version>
      <configuration>
        <mainClass>${main.class}</mainClass>
      </configuration>
    </plugin>

    <plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>exec-maven-plugin</artifactId>
      <version>3.1.0</version>
      <configuration>
        <mainClass>${main.class}</mainClass>
      </configuration>
    </plugin>
  </plugins>
</build>
  </project>
